### ISSUE TITLE
Antragsteller bei A0239/23 ist falsch

### ISSUE THREAD

**Issue by Micha-Richter** [code-for-magdeburg/StadtratWatch-web#98]
Scheinbar sind die Ausgangsdaten unter src/scripts/generate-data-assets/configs/2023-10-16/session-scan-2023-10-16.json schon falsch erfasst/erzeugt worden!?

**Comment by JensWinter** [comment]
Hi Micha!

Danke für diesen Hinweis. Die Angaben sind tatsächlich korrekt so.
Bei A0239/23 handelt es sich zwar um einen Antrag der CDU. Allerdings war die Abstimmung, die an der Stelle gemessen wurde, ein Geschäftsordnungsantrag der Linken. Die Fraktion hatte eine Überweisung in verschiedene Ausschüsse beantragt. Und darüber wurde zu dem Zeitpunkt abgestimmt. Hier mal die Einbringung: https://www.youtube.com/live/ib8L3H72uvY?si=qAF52_dPzoFsGns4&t=6772

Das passiert sehr häufig. Und ich müsste mir etwas einfallen lassen, damit das besser erkennbar ist.

**Comment by Micha-Richter** [comment]
Hallo Jens,

ah...wieder was gelernt! Konnte ich nicht erkennen bzw hab nicht genau genug hingehört.

Woher kommen die Daten in generate-data-assets/..? Extrahiert ihr die direkt aus den Videos? (hab irgendwo X-/Y-Positionsangaben gesehen)

**Comment by JensWinter** [comment]
Es ist relativ unspektakulär: Ich habe mir ein Tool geschrieben, das aus Standbildern der Videoauzeichnung die Abstimmungskonstellation erkennt. Das ist der einfache Teil.

Es ist dennoch viel Handarbeit notwendig. Z.B. wegen solcher Fälle, wie du ihn beschrieben hast. Das kann man nämlich so nicht erkennen. Hierfür gehe ich das Video in einem manuellen Review-Prozess durch und gleiche noch mit dem schriftlichen Protokoll ab, welches im Ratsinformationssystem zur Verfügung gestellt wird.

Vielleicht kann man hier irgendwann mal mit einer KI nachhelfen. :)

**Comment by Micha-Richter** [comment]
Danke für die Infos, Jens!!
